### ISSUE TITLE
server based imap aggregator with filters?

### ISSUE THREAD

**Issue by drevicko** [dteoh/tidal-app#1]
Hi Doug,

I'm looking for an open source imap aggregator that can do message filtering (ie: move messages to subfolders aka thunderbird filters). Something like (the imap part of) https://launch.unifiedinbox.com/.

I was hoping thunderbird might have such a thing (something like thunderbird without a gui), but that doesn't seem to be the case.

Is tidal-app a potential candidate? Or at least a beginning from which to start?
Do you know of a better option?

ps: I'd have sent this as a message, but github doesn't seen to have such a thing - correct me if I'm wrong!

**Comment by dteoh** [comment]
Nope, tidal-app does nothing of the sort.

I am not familiar with server side email aggregators. Maybe you can have a look at Zimbra or Mailpile (https://www.mailpile.is/)? It sounds like you want to host your own email server?

**Comment by drevicko** [comment]
Sorry I didn't close this myself - got distracted!
What I'm after is a bit different to my own email server, though some may achieve it.
Basically I want to be able to keep imap mail filters (for moving various emails into appropriate folders mostly) all in one place, and have them applied whenever new mail arrives. The mail itself can stay where it's already hosted. 

Thunderbird almost does this (with lots of extra baggage!), but it doesn't work without a GUI and isn't all that stable. I keep it running on an office machine, but have to restart it regularly, which I've not found a way to do remotely (without ssh -X or other remote desktop, but that's a pain!)

Thanks for the suggestions though. Mailpile looks like it could achieve this in time, though it's main purpose is different.
